#!/bin/zsh

set -e

if [ -d xml/ ]; then
  # Control will enter here if xml/ exists.
  echo "Will remove the old data"
  rm -rf xml
fi

mkdir xml

for ((i=1;i<101;i++)); do
    mkdir xml/data_exp_$i
    echo "Creating data for Exp $i"
    python -m src.random_ball_falling \
      --drawContactPoints \
      --config_build --hz 300 \
      --velocityIterations 8 \
      --positionIterations 8 \
      --export_path xml/data_exp_$i
  done
